### ISSUE TITLE
Demo issue

### ISSUE THREAD

**Issue by Paolo07700** [starstorms9/shape#18]
Hi there!
The demo link is not fonctionnal...

**Comment by starstorms9** [comment]
Hey! Apologies I had to take down the demo as I didn't have the necessary time to maintain it, updated the readme to remove the link.

**Comment by Paolo07700** [comment]
> Hey! Apologies I had to take down the demo as I didn't have the necessary time to maintain it, updated the readme to remove the link.

so how can we try?

**Comment by starstorms9** [comment]
I uploaded the trained model weights and all of the code that ran the demo so if you download everything from the repo it's enough get it running locally  with pretrained models if you would like! The streamlit demo app actually directly used the model weights uploaded here on the repo as well as the requirements.txt to build the python environment.
