### ISSUE TITLE
datanexus.xyz isn't reachable

### ISSUE THREAD

**Issue by tianyilt** [starstorms9/shape#6]
Hi, thanks for the great project of 3D generative design. I'm a researcher of generative design with deep generative models. The failure of the demo web makes it hard to use and enjoy this great work easily(difficulties such as over 100GB dataset and no pre-trained model). Could you have plans to fix it? Sincerely thanks!

**Comment by starstorms9** [comment]
Hey! Apologies, the demo is down now as it was a bit hard to maintain and I didn't have the necessary time. It is indeed hard to train it but I have uploaded the model weights so the offline demo should still work with a little configuration.
